server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: oracle.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/groupware?currentSchema=default_schema
#    url: jdbc:log4jdbc:postgresql://localhost:5432/groupware?currentSchema=default_schema
    url: jdbc:postgresql://34.64.187.254/user_db
    username: user01
    password: 1234

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
  
# Mybatis 설정
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: com.ds.gwapp
  # mapper location - 바라볼 xml 파일을 지정합니다.
  mapper-locations: classpath:mapper/*.xml
  # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
  configuration:
    map-underscore-to-camel-case: true
    
    
logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: info
      resultset: info
      connection: info
