spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://url:5432/groupware?currentSchema=default_schema
    username: user01
    password: 1234



# Mybatis 설정
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: com.ds.gwapp
  # mapper location - 바라 볼 xml 파일을 지정합니다.
  mapper-locations: classpath:mapper/*.xml
  # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
  configuration:
    map-underscore-to-camel-case: true